### ISSUE TITLE
Violence section addition and UX suggestions.

### ISSUE THREAD

**Issue by lkarvec** [destinygg/destinypositions#35]
Addition request:
Probably should clarify that you also believe in self defense outside of political violence, and where you stand with [Castle Doctrine policy](https://en.wikipedia.org/wiki/Castle_doctrine).  You could probably also extrapolate this into stances on Gun Control.

UX suggestions:
Might also want to put "_Protesting and Rioting_" and "_Defense of Property_" as subsections of Violence, as you have with "_Socialism_" sections.  Seems related.

You could probably also create a "_Stock Market_" tab for the GME stuff too.

**Comment by revelsix** [comment]
GME has been moved to current events as of #43 , all that's left is if @Steven-Bonnell-II wants to add castle doctrine/gun control stuff (Bonus meme for Destiny: if you add "closes #issue number" to the description of a pull request it automatically closes the issue :) )
