### ISSUE TITLE
Add a license to repository since there currently is none

### ISSUE THREAD

**Issue by tojba** [destinygg/destinypositions#8]
Since there is no license it means that the default copyright laws apply to the code/text in this repository. 
To read more about what/why/how you can look at the following links:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license
https://choosealicense.com/

**Comment by revelsix** [comment]
Should we just use the same (or slightly modified) license as the main destiny.gg site? @ILiedAboutCake

**Comment by ILiedAboutCake** [comment]
The base of Docusaurus and recent DGG projects have been licensed as MIT, and we will likely follow that pattern with this repo.
