### ISSUE TITLE
About

### ISSUE THREAD

**Issue by lavrentidan** [destinygg/destinypositions#93]
I think that the 'About' page should be a little more fleshed out by including a brief introduction about who you are and what you do. The 'About' page as it currently stands just starts right off the bat with being defensive about your positions. What I'm picturing in my head are outsiders like the Atlanta DSA hearing about this "Destiny" guy while getting links to this page and still not really knowing much about who exactly "Destiny" is.

I believe a better structure would look something like this:

# About

## Who I am / who is destiny?
(small blurb about streaming career)
(would be nice to have a picture of you in this section as well)

## Projects / Political advocacy
(List of achievements and/or projects such as Georgia canvassing, possibly even Omaha canvassing as well )

## Why I made this website/blog
(Just include everything you already have under this section)

**Comment by revelsix** [comment]
Can either @lavrentidan  or @ILiedAboutCake close this, it's been resolved as of #109
